name: build-daily

on:
  schedule:
    - cron: '35 20 * * 1-5'   # 평일 KST 새벽 실행
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

concurrency:
  group: daily-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Preflight
        run: |
          test -n "${{ secrets.POLYGON_API_KEY }}" || (echo "MISSING POLYGON_API_KEY" && exit 1)
          test -n "${{ secrets.OPENAI_API_KEY }}"  || (echo "MISSING OPENAI_API_KEY" && exit 1)
          ls -la

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Generate bundle (Polygon)
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
        run: |
          set -e
          python fetch_polygon_toplists.py
          echo "BUNDLE=$(ls -d out/* | sort | tail -1)/bundle.json" >> $GITHUB_ENV
          echo "BUNDLE path: $BUNDLE"

      - name: Syntax check
        run: python -m py_compile summarize_with_openai.py

      - name: Summarize with GPT-5 (JP)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-5
          OPENAI_MAX_OUTPUT_TOKENS: "6500"
        run: |
          set -e
          test -f "$BUNDLE" || (echo "Bundle not found: $BUNDLE" && exit 1)
          python summarize_with_openai.py --bundle "$BUNDLE" --out note_post_llm.md

      - name: Publish to public/
        run: |
          set -e
          mkdir -p public/daily
          DATE=$(python -c 'import json,sys;print(json.load(open(sys.argv[1]))["date"])' "$BUNDLE")
          cp note_post_llm.md public/daily/latest.md
          cp "$BUNDLE"        public/daily/latest.json
          cp note_post_llm.md "public/daily/${DATE}.md"
          cp "$BUNDLE"        "public/daily/${DATE}.json"

      - name: Commit and push (rebase)
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add public/daily note_post_llm.md || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "daily: $(date -u +'%Y-%m-%d')"
          git pull --rebase origin main
          git push
