name: daily-jpx
on:
  schedule:
    - cron: "35 20 * * 1-5"    # JP 장 마감 후
  workflow_dispatch:

permissions:
  contents: write

jobs:
  jpx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance requests lxml openai

      - name: Bootstrap JPX universe
        run: |
          python scripts/bootstrap_jpx_universe.py || true
          ls -l data || true

      - name: Build JPX toplists
        env:
          MIN_PRICE_JPY: "1000"
        run: |
          python fetch_jpx_toplists.py
          echo "BUNDLE_JPX=$(ls -d out_jpx/* | sort | tail -1)/bundle.json" >> "$GITHUB_ENV"

      - name: Export DATE from bundle
        run: |
          DATE=$(python -c 'import json,os;print(json.load(open(os.environ["BUNDLE_JPX"],encoding="utf-8"))["date"])')
          echo "DATE=$DATE" >> "$GITHUB_ENV"

      - id: preflight
        name: Preflight size guard
        run: |
          SKIP=$(python -c 'import json,os;d=json.load(open(os.environ["BUNDLE_JPX"],encoding="utf-8"));print("1" if len(d.get("lists",{}).get("universe_top600_by_dollar",[]))<100 else "0")')
          echo "skip_llm=$SKIP" >> "$GITHUB_OUTPUT"

      - name: Summarize with GPT-5 (JP)
        if: steps.preflight.outputs.skip_llm == '0'
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: gpt-5
          OPENAI_MAX_OUTPUT_TOKENS: "8000"
          MIN_PRICE_JPY: "1000"
        run: |
          python summarize_with_openai_jp.py --bundle "$BUNDLE_JPX" --out note_post_llm_jpx.md

      - name: Publish to public/jpx
        run: |
          mkdir -p public/jpx
          cp "$BUNDLE_JPX" "public/jpx/${DATE}.json"
          cp "$BUNDLE_JPX" public/jpx/latest.json
          if [ -f note_post_llm_jpx.md ]; then
            cp note_post_llm_jpx.md "public/jpx/${DATE}.md"
            cp note_post_llm_jpx.md public/jpx/latest.md
          fi

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git pull --rebase
          git add public/jpx data/*.csv data/*.txt out_jpx || true
          git commit -m "JPX daily: ${DATE}" || true
          git push
