name: Fetch JPX Universe CSV

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    env:
      TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # lockfile 없어도 됨. tsx만 dev로 설치
      - name: Install minimal deps
        run: |
          npm install -D tsx

      # public 폴더 보장
      - name: Ensure public dir
        run: mkdir -p public

      # 스크립트 실행 (ts-node 대신 tsx로 간단히)
      - name: Generate CSV
        run: |
          npx tsx scripts/fetch_jpx_full.ts --limit=5000
          echo "Preview head:"
          head -n 5 public/jpx_universe.csv || true
          echo "Total lines:"
          wc -l public/jpx_universe.csv || true

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/jpx_universe.csv
          git commit -m "chore: update JPX universe CSV" || echo "no changes to commit"
          # 원격이 앞서 있을 때를 대비해 리베이스 후 푸시
          git pull --rebase || true
          git push
