name: Fetch JPX Universe CSV (PR)

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch-and-pr:
    runs-on: ubuntu-latest
    env:
      TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - run: npm install -D tsx

      - run: mkdir -p public

      - name: Generate CSV
        run: |
          npx tsx scripts/fetch_jpx_full.ts --limit=5000
          head -n 5 public/jpx_universe.csv || true
          wc -l public/jpx_universe.csv || true

      - name: Create branch, commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B update/jpx-universe
          git add public/jpx_universe.csv
          git commit -m "chore: update JPX universe CSV" || echo "no changes to commit"
          git push -u origin update/jpx-universe || true

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: update/jpx-universe
          title: "chore: update JPX universe CSV"
          body: "Automated update of JPX universe."
          commit-message: "chore: update JPX universe CSV"
          labels: data
