name: Fetch JPX Universe CSV (commit)

on:
  workflow_dispatch: {}

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 커밋/푸시 권한

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show versions
        run: |
          echo "PWD=$(pwd)"
          node -v
          npm -v

      - name: Fetch JPX from TwelveData
        env:
          TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
        run: |
          npm run fetch:jpx || true
          echo "== AFTER WRITE =="
          ls -al public || true
          echo "== ROW COUNT =="
          wc -l public/jpx_universe.csv || true

      - name: Commit & Push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain public/jpx_universe.csv)" ]; then
            git add public/jpx_universe.csv
            git commit -m "chore: update JPX universe CSV"
            git push
          else
            echo "No changes to commit."
          fi
