name: Fetch JPX Universe CSV

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    env:
      TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps (generate package-lock.json)
        run: |
          npm install --no-fund --no-audit
          npm install -D ts-node

      - name: Ensure tsconfig for scripts exists
        run: |
          if [ ! -f tsconfig.scripts.json ]; then
            cat > tsconfig.scripts.json <<'JSON'
            {
              "extends": "./tsconfig.json",
              "compilerOptions": {
                "target": "ES2020",
                "module": "NodeNext",
                "moduleResolution": "NodeNext",
                "esModuleInterop": true,
                "resolveJsonModule": true,
                "skipLibCheck": true,
                "strict": false,
                "types": ["node"]
              },
              "include": ["scripts/**/*"]
            }
            JSON
          fi

      - name: Generate CSV
        run: |
          npx ts-node --project tsconfig.scripts.json scripts/fetch_jpx_full.ts --limit=5000

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/jpx_universe.csv package-lock.json
          git commit -m "chore: update JPX universe CSV" || echo "no changes to commit"
          git push
