name: Fetch JPX Universe CSV (commit)

on:
  workflow_dispatch: {}
  # 원하면 스케줄도 추가 가능 (예: 평일 20:15 JST = 11:15 UTC)
  # schedule:
  #   - cron: "15 11 * * 1-5"

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Show versions
        run: |
          echo "PWD=$(pwd)"
          node -v
          npm -v

      - name: Fetch JPX from TwelveData
        env:
          TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}
        run: |
          npm run fetch:jpx

      # (선택) 테마/브리프 보강 스텝 — 스크립트 파일이 있을 때만 동작
      - name: Enrich CSV (theme/brief)
        run: |
          if [ -f scripts/enrich_universe.mjs ]; then
            npm run enrich:jpx
          else
            echo "enrich_universe.mjs not found. Skip."
          fi

      - name: Show CSV stats
        run: |
          echo "== AFTER WRITE ==" && ls -al public || true
          echo "== ROW COUNT ==" && wc -l public/jpx_universe.csv || true

      - name: Commit & Push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain public/jpx_universe.csv)" ]; then
            git add public/jpx_universe.csv
            git commit -m "chore: update JPX universe CSV"
            git push
          else
            echo "No changes to commit."
          fi
